# Generated by Django 2.0.7 on 2018-07-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dani_odsustva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Od_dana', models.DateField()),
                ('Do_data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Deo_sredstva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procenat_promene', models.DecimalField(decimal_places=2, max_digits=3)),
                ('vrednost', models.DecimalField(decimal_places=2, max_digits=30)),
                ('datum_promene', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Importovan_dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('ekstenzija', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projekat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Projekat',
                'verbose_name_plural': 'Projekti',
            },
        ),
        migrations.CreateModel(
            name='Projekat_Zaposleni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_datuma', models.DateField()),
                ('do_datuma', models.DateField()),
                ('projekat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ljudi.Projekat')),
            ],
        ),
        migrations.CreateModel(
            name='Sredstvo_za_rad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('vrednost', models.DecimalField(decimal_places=2, max_digits=30)),
                ('datum_kupovine', models.DateField()),
                ('deo_sredstva', models.ManyToManyField(related_name='je_deo', through='ljudi.Deo_sredstva', to='ljudi.Sredstvo_za_rad')),
            ],
        ),
        migrations.CreateModel(
            name='Template_resenja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tip_odsustva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('Opis', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zaposleni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JMBG', models.CharField(blank=True, max_length=25, null=True)),
                ('ime_prezime', models.CharField(max_length=50)),
                ('adresa', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('A', 'Aktivan'), ('N', 'Neaktivan')], max_length=1)),
                ('nadredjeni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ljudi.Zaposleni')),
            ],
            options={
                'verbose_name': 'Zaposleni',
                'verbose_name_plural': 'Zaposleni',
            },
        ),
        migrations.AddField(
            model_name='template_resenja',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template', to='ljudi.Tip_odsustva'),
        ),
        migrations.AddField(
            model_name='sredstvo_za_rad',
            name='zaposleni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Sredstva_za_rad', to='ljudi.Zaposleni'),
        ),
        migrations.AddField(
            model_name='projekat_zaposleni',
            name='zaposleni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ljudi.Zaposleni'),
        ),
        migrations.AddField(
            model_name='projekat',
            name='zaposleni',
            field=models.ManyToManyField(related_name='projekti', through='ljudi.Projekat_Zaposleni', to='ljudi.Zaposleni'),
        ),
        migrations.AddField(
            model_name='deo_sredstva',
            name='iz_sredstva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iz_sredstva', to='ljudi.Sredstvo_za_rad'),
        ),
        migrations.AddField(
            model_name='deo_sredstva',
            name='u_sredstvo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='u_sredstvo', to='ljudi.Sredstvo_za_rad'),
        ),
        migrations.AddField(
            model_name='dani_odsustva',
            name='dokument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dani_odsustva', to='ljudi.Importovan_dokument'),
        ),
        migrations.AddField(
            model_name='dani_odsustva',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dani_odsustva', to='ljudi.Tip_odsustva'),
        ),
        migrations.AddField(
            model_name='dani_odsustva',
            name='zaposleni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dani_odsustva', to='ljudi.Zaposleni'),
        ),
    ]
