# Generated by Django 2.0.7 on 2018-07-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljudi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sredstvo_za_rad',
            name='deo_sredstva',
            field=models.ManyToManyField(blank=True, related_name='je_deo', through='ljudi.Deo_sredstva', to='ljudi.Sredstvo_za_rad'),
        ),
    ]
