# Generated by Django 2.0.7 on 2018-07-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ljudi', '0002_auto_20180719_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dani_odsustva',
            name='dokument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dani_odsustva', to='ljudi.Importovan_dokument'),
        ),
    ]
