# Generated by Django 2.0.7 on 2018-07-30 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ljudi', '0004_auto_20180720_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deo_sredstva',
            name='datum_promene',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deo_sredstva',
            name='iz_sredstva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iz_sredstva', to='ljudi.Sredstvo_za_rad'),
        ),
        migrations.AlterField(
            model_name='deo_sredstva',
            name='procenat_promene',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='deo_sredstva',
            name='u_sredstvo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='u_sredstvo', to='ljudi.Sredstvo_za_rad'),
        ),
        migrations.AlterField(
            model_name='deo_sredstva',
            name='vrednost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='sredstvo_za_rad',
            name='deo_sredstva',
            field=models.ManyToManyField(blank=True, null=True, related_name='je_deo', through='ljudi.Deo_sredstva', to='ljudi.Sredstvo_za_rad'),
        ),
    ]
